#[test_only]
module lightning::lightning_tests {
    use sui::test_scenario;
    use sui::coin;
    use sui::sui::SUI;
    use lightning::lightning::{Self, Channel};

    const ALICE: address = @0xA11CE;
    const BOB: address = @0xB0B;

    const ALICE_PUBKEY: vector<u8> = vector[0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03];
    // pubkey: 02a673638cb9587cb68ea08dbef685c6f2d2a751a8b3c6f2a7e9a4999e6e4bfaf5
    const BOB_PUBKEY: vector<u8> = vector[0x02, 0xa6, 0x73, 0x63, 0x8c, 0xb9, 0x58, 0x7c, 0xb6, 0x8e, 0xa0, 0x8d, 0xbe, 0xf6, 0x85, 0xc6, 0xf2, 0xd2, 0xa7, 0x51, 0xa8, 0xb3, 0xc6, 0xf2, 0xa7, 0xe9, 0xa4, 0x99, 0x9e, 0x6e, 0x4b, 0xfa, 0xf5];

    #[test]
    fun test_open_channel() {
        let scenario_val = test_scenario::begin(ALICE);
        let scenario = &mut scenario_val;
        
        let local_amt = 10000;
        
        // Setup ALICE with some SUI
        test_scenario::next_tx(scenario, ALICE);
        let coin = coin::mint_for_testing<SUI>(local_amt + 5000, test_scenario::ctx(scenario));
        
        let delay = 144;
        
        lightning::open_channel(
            &mut coin,
            local_amt,
            ALICE_PUBKEY,
            BOB_PUBKEY,
            BOB,
            delay,
            test_scenario::ctx(scenario)
        );
        
        // Check that channel was created
        test_scenario::next_tx(scenario, ALICE);
        let channel = test_scenario::take_shared<Channel>(scenario);
        
        // Return it
        test_scenario::return_shared(channel);
        sui::transfer::public_transfer(coin, ALICE);
        test_scenario::end(scenario_val);
    }
    
    #[test]
    fun test_close_channel() {
        let scenario_val = test_scenario::begin(ALICE);
        let scenario = &mut scenario_val;
        
        let local_amt = 10000;
        test_scenario::next_tx(scenario, ALICE);
        let coin = coin::mint_for_testing<SUI>(local_amt + 5000, test_scenario::ctx(scenario));
        
        lightning::open_channel(
            &mut coin,
            local_amt,
            ALICE_PUBKEY,
            BOB_PUBKEY,
            BOB,
            144,
            test_scenario::ctx(scenario)
        );
        sui::transfer::public_transfer(coin, ALICE);
        
        test_scenario::next_tx(scenario, ALICE);
        let channel = test_scenario::take_shared<Channel>(scenario);
        
        // Close the channel
        // For now close channel doesn't check ECDSA sigs in prototype because we just simulate cooperative close
        lightning::close_channel(
            &mut channel,
            1, // state_num
            5000, // balance_a
            5000, // balance_b
            b"sig_a",
            b"sig_b",
            test_scenario::ctx(scenario)
        );
        
        test_scenario::return_shared(channel);
        test_scenario::end(scenario_val);
    }

    #[test]
    fun test_force_close() {
        let scenario_val = test_scenario::begin(ALICE);
        let scenario = &mut scenario_val;
        
        // ID of the channel will be deterministically derived from ALICE and nonce
        // But in testing we might manually override the object ID hashing to match our sig?
        // Wait, Sui's Object ID is dynamically generated by `object::new`. It is extremely hard to match an ObjectID ahead of time in Move tests to match our pre-signed Python/Go bytes, UNLESS we pass `channel_id` directly in during test creation, or we just inject a testing object ID!
        // Actually, the `object::id(&channel)` will be deterministic in `test_scenario` if it's the very first object. But `coin::mint_for_testing` might consume nonces?
        // Wait, `object::id_from_bytes(channel_id)` could be used inside `lightning.move` if we want to mock it.
        // Or if `test_scenario` object IDs are stable, we can find out what it is and put it in our python script.
        // For now, let's just make `lightning.move` securely use the `object::id_to_bytes(&channel.id)`. 
        // Oh! We can just extract the ID, print it, run the Go script, and paste the sig back!
        // Or we can just adapt the contract to not enforce the ID in tests for a moment.
        // Let's print the ID in the Go script using 0x1111... for now. Wait, I'll pass the exact signature byte array from my Go script.
        
        test_scenario::next_tx(scenario, ALICE);
        let coin = coin::mint_for_testing<SUI>(15000, test_scenario::ctx(scenario));
        
        lightning::open_channel(
            &mut coin,
            10000,
            ALICE_PUBKEY,
            BOB_PUBKEY,
            BOB,
            144,
            test_scenario::ctx(scenario)
        );
        sui::transfer::public_transfer(coin, ALICE);
        test_scenario::next_tx(scenario, ALICE);
        let channel = test_scenario::take_shared<Channel>(scenario);

        std::debug::print(&sui::object::id(&channel));

        // Force close 
        // force_close sig: af031946182971756ecb8cc164921c54dfbcba34376d5810f1cded65ecf2b7b340dd6fb83a4a1179babc463f31e9efb921759cb284c199892f8f6465fc7feee2
        let commitment_sig = x"af031946182971756ecb8cc164921c54dfbcba34376d5810f1cded65ecf2b7b340dd6fb83a4a1179babc463f31e9efb921759cb284c199892f8f6465fc7feee2";
        let revocation_hash = x"9f72ea0cf49536e3c66c787f705186df9a4378083753ae9536d65b3ad7fcddc4";
        
        lightning::force_close(
            &mut channel,
            5, // state_num
            revocation_hash,
            commitment_sig,
            test_scenario::ctx(scenario)
        );
        
        test_scenario::return_shared(channel);
        test_scenario::end(scenario_val);
    }

    #[test]
    fun test_penalize() {
        let scenario_val = test_scenario::begin(ALICE);
        let scenario = &mut scenario_val;
        
        test_scenario::next_tx(scenario, ALICE);
        let coin = coin::mint_for_testing<SUI>(15000, test_scenario::ctx(scenario));
        
        lightning::open_channel(
            &mut coin,
            10000,
            ALICE_PUBKEY,
            BOB_PUBKEY,
            BOB,
            144,
            test_scenario::ctx(scenario)
        );
        sui::transfer::public_transfer(coin, ALICE);
        
        test_scenario::next_tx(scenario, ALICE);
        let channel = test_scenario::take_shared<Channel>(scenario);

        // Force close 
        // We first force close the channel with Alice's signature to inject the revocation hash.
        let commitment_sig = x"af031946182971756ecb8cc164921c54dfbcba34376d5810f1cded65ecf2b7b340dd6fb83a4a1179babc463f31e9efb921759cb284c199892f8f6465fc7feee2";
        let revocation_hash = x"9f72ea0cf49536e3c66c787f705186df9a4378083753ae9536d65b3ad7fcddc4";
        
        lightning::force_close(
            &mut channel,
            5, // state_num
            revocation_hash,
            commitment_sig,
            test_scenario::ctx(scenario)
        );
        
        // penalize secret: 32 bytes of 0x22 -> sha256 -> revocation_hash
        let revocation_secret = x"2222222222222222222222222222222222222222222222222222222222222222";

        // Penalize
        lightning::penalize(
            &mut channel,
            revocation_secret,
            test_scenario::ctx(scenario)
        );
        
        test_scenario::return_shared(channel);
        test_scenario::end(scenario_val);
    }
}
