package evmnotify

import (
	_ "embed"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

// channelManagerABIJSON is the ABI of the deployed ChannelManager contract,
// generated by `forge inspect ChannelManager abi`. It is embedded so the
// adapter can pack settlement calls and parse event logs without a code-gen
// step.
//
//go:embed channelmanager_abi.json
var channelManagerABIJSON string

// ChannelManagerABI is the parsed ChannelManager ABI.
var ChannelManagerABI = mustParseABI(channelManagerABIJSON)

// erc20BalanceABI is the minimal ABI fragment the adapters need from an ERC20:
// balance/decimals reads plus approve (the ChannelManager pulls deposits via
// transferFrom, so the funder must grant an allowance before openChannel).
const erc20BalanceABI = `[{"constant":true,"inputs":[{"name":"account",` +
	`"type":"address"}],"name":"balanceOf","outputs":[{"name":"",` +
	`"type":"uint256"}],"stateMutability":"view","type":"function"},` +
	`{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"",` +
	`"type":"uint8"}],"stateMutability":"view","type":"function"},` +
	`{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"",` +
	`"type":"string"}],"stateMutability":"view","type":"function"},` +
	`{"constant":false,"inputs":[{"name":"spender","type":"address"},` +
	`{"name":"amount","type":"uint256"}],"name":"approve","outputs":` +
	`[{"name":"","type":"bool"}],"stateMutability":"nonpayable",` +
	`"type":"function"},` +
	`{"constant":false,"inputs":[{"name":"to","type":"address"},` +
	`{"name":"amount","type":"uint256"}],"name":"transfer","outputs":` +
	`[{"name":"","type":"bool"}],"stateMutability":"nonpayable",` +
	`"type":"function"}]`

// ERC20ABI is the parsed minimal ERC20 ABI (balanceOf + decimals + approve +
// transfer).
var ERC20ABI = mustParseABI(erc20BalanceABI)

// Event topic-0 hashes, keccak256 of the canonical event signatures. The
// adapter filters logs by these to dispatch to the right resolver.
var (
	TopicChannelOpened = crypto.Keccak256Hash([]byte(
		"ChannelOpened(bytes32,address,address,uint256,uint256)",
	))
	TopicChannelClosed = crypto.Keccak256Hash([]byte(
		"ChannelClosed(bytes32,uint256,uint256)",
	))
	TopicUnilateralCloseInitiated = crypto.Keccak256Hash([]byte(
		"UnilateralCloseInitiated(bytes32,address,uint256,uint256," +
			"uint256,uint256)",
	))
	TopicChannelPunished = crypto.Keccak256Hash([]byte(
		"ChannelPunished(bytes32,address,uint256)",
	))
	TopicHTLCClaimed = crypto.Keccak256Hash([]byte(
		"HTLCClaimed(bytes32,uint256,bytes32)",
	))
	TopicHTLCTimeout = crypto.Keccak256Hash([]byte(
		"HTLCTimeout(bytes32,uint256)",
	))
	TopicFundsDistributed = crypto.Keccak256Hash([]byte(
		"FundsDistributed(bytes32,uint256,uint256)",
	))
)

// mustParseABI parses an ABI JSON string, panicking on error (package-level
// initialisation only).
func mustParseABI(s string) abi.ABI {
	parsed, err := abi.JSON(strings.NewReader(s))
	if err != nil {
		panic("evmnotify: invalid embedded ABI: " + err.Error())
	}

	return parsed
}

// PackOpenChannel ABI-encodes an openChannel(salt, counterparty,
// localFundingAmount, remoteFundingAmount, counterpartySig) call.
// counterpartySig may be empty for single-funded opens (remoteAmt == 0); it is
// the counterparty's EIP-712 OpenChannel consent signature otherwise.
func PackOpenChannel(salt [32]byte, counterparty common.Address,
	localAmt, remoteAmt *big.Int, counterpartySig []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"openChannel", salt, counterparty, localAmt, remoteAmt,
		counterpartySig,
	)
}

// PackCloseChannel ABI-encodes a closeChannel call for a cooperative close.
func PackCloseChannel(channelID [32]byte, nonce, finalA, finalB *big.Int,
	sigA, sigB []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"closeChannel", channelID, nonce, finalA, finalB, sigA, sigB,
	)
}

// PackForceClose ABI-encodes a forceClose call.
func PackForceClose(channelID [32]byte, nonce, balA, balB *big.Int,
	htlcsHash [32]byte, sig []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"forceClose", channelID, nonce, balA, balB, htlcsHash, sig,
	)
}

// PackDistributeFunds ABI-encodes a distributeFunds call.
func PackDistributeFunds(channelID [32]byte) ([]byte, error) {
	return ChannelManagerABI.Pack("distributeFunds", channelID)
}

// PackPenalize ABI-encodes a penalize call.
func PackPenalize(channelID [32]byte, correctNonce, balA, balB *big.Int,
	htlcsHash [32]byte, correctSig []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"penalize", channelID, correctNonce, balA, balB, htlcsHash,
		correctSig,
	)
}

// EvmHTLCArg mirrors the contract's HTLC struct in the field order and types
// go-ethereum's ABI packer expects for the tuple.
type EvmHTLCArg struct {
	Index     *big.Int
	Amount    *big.Int
	Hashlock  [32]byte
	Timelock  uint32
	Recipient common.Address
}

// PackClaimHtlc ABI-encodes a claimHtlc(channelId, htlc, merkleProof,
// preimage) call.
func PackClaimHtlc(channelID [32]byte, htlc EvmHTLCArg,
	merkleProof [][32]byte, preimage [32]byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"claimHtlc", channelID, htlc, merkleProof, preimage,
	)
}

// PackTimeoutHtlc ABI-encodes a timeoutHtlc(channelId, htlc, merkleProof)
// call.
func PackTimeoutHtlc(channelID [32]byte, htlc EvmHTLCArg,
	merkleProof [][32]byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"timeoutHtlc", channelID, htlc, merkleProof,
	)
}

// PackApprove ABI-encodes an ERC20 approve(spender, amount) call.
func PackApprove(spender common.Address, amount *big.Int) ([]byte, error) {
	return ERC20ABI.Pack("approve", spender, amount)
}

// PackTransfer ABI-encodes an ERC20 transfer(to, amount) call.
func PackTransfer(to common.Address, amount *big.Int) ([]byte, error) {
	return ERC20ABI.Pack("transfer", to, amount)
}

// PackToken ABI-encodes the ChannelManager token() getter.
func PackToken() ([]byte, error) {
	return ChannelManagerABI.Pack("token")
}

// UnpackToken decodes the address result of the token() getter.
func UnpackToken(data []byte) (common.Address, error) {
	vals, err := ChannelManagerABI.Unpack("token", data)
	if err != nil {
		return common.Address{}, err
	}
	if len(vals) != 1 {
		return common.Address{}, fmt.Errorf("evmnotify: unexpected " +
			"token return")
	}
	addr, ok := vals[0].(common.Address)
	if !ok {
		return common.Address{}, fmt.Errorf("evmnotify: token not " +
			"an address")
	}

	return addr, nil
}

// Channel status values, mirroring the contract's IChannelManager.Status
// enum: NONEXISTENT, OPEN, CLOSING_COOP, CLOSING_UNILATERAL, CLOSED.
const (
	ChannelStatusNonexistent       uint8 = 0
	ChannelStatusOpen              uint8 = 1
	ChannelStatusClosingCoop       uint8 = 2
	ChannelStatusClosingUnilateral uint8 = 3
	ChannelStatusClosed            uint8 = 4
)

// PackChannel ABI-encodes the channels(bytes32) getter call.
func PackChannel(channelID [32]byte) ([]byte, error) {
	return ChannelManagerABI.Pack("channels", channelID)
}

// UnpackChannelStatus decodes the channels(bytes32) getter result and returns
// the channel's Status field (index 3 of the returned struct).
func UnpackChannelStatus(data []byte) (uint8, error) {
	vals, err := ChannelManagerABI.Unpack("channels", data)
	if err != nil {
		return 0, err
	}
	if len(vals) < 4 {
		return 0, fmt.Errorf("evmnotify: unexpected channels return")
	}
	st, ok := vals[3].(uint8)
	if !ok {
		return 0, fmt.Errorf("evmnotify: channel status not a uint8")
	}

	return st, nil
}

// UnpackUnilateralClose decodes the non-indexed data of a
// UnilateralCloseInitiated log into the fields a watchtower needs to judge a
// breach: the broadcaster, the nonce of the broadcast state, and the challenge
// deadline (unix seconds). channelId is the indexed topic, not part of data.
func UnpackUnilateralClose(data []byte) (broadcaster common.Address,
	nonce, challengeExpiry uint64, err error) {

	vals, err := ChannelManagerABI.Events["UnilateralCloseInitiated"].
		Inputs.NonIndexed().Unpack(data)
	if err != nil {
		return common.Address{}, 0, 0, err
	}
	// broadcaster, nonce, balanceA, balanceB, challengeExpiry.
	if len(vals) != 5 {
		return common.Address{}, 0, 0, fmt.Errorf("evmnotify: " +
			"unexpected UnilateralCloseInitiated data")
	}
	bc, okBC := vals[0].(common.Address)
	n, okN := vals[1].(*big.Int)
	ce, okCE := vals[4].(*big.Int)
	if !okBC || !okN || !okCE {
		return common.Address{}, 0, 0, fmt.Errorf("evmnotify: " +
			"UnilateralCloseInitiated field types")
	}

	return bc, n.Uint64(), ce.Uint64(), nil
}

// UnpackChannelOpened decodes the non-indexed data of a ChannelOpened log,
// returning the two raw base-unit deposits.
func UnpackChannelOpened(data []byte) (balanceA, balanceB *big.Int,
	err error) {

	vals, err := ChannelManagerABI.Events["ChannelOpened"].Inputs.
		NonIndexed().Unpack(data)
	if err != nil {
		return nil, nil, err
	}
	// participantA, participantB, balanceA, balanceB.
	if len(vals) != 4 {
		return nil, nil, fmt.Errorf("evmnotify: unexpected " +
			"ChannelOpened data")
	}

	balanceA, okA := vals[2].(*big.Int)
	balanceB, okB := vals[3].(*big.Int)
	if !okA || !okB {
		return nil, nil, fmt.Errorf("evmnotify: ChannelOpened " +
			"balances not uint256")
	}

	return balanceA, balanceB, nil
}

// PackBalanceOf ABI-encodes an ERC20 balanceOf(account) call.
func PackBalanceOf(account common.Address) ([]byte, error) {
	return ERC20ABI.Pack("balanceOf", account)
}

// PackDecimals ABI-encodes an ERC20 decimals() call.
func PackDecimals() ([]byte, error) {
	return ERC20ABI.Pack("decimals")
}

// PackSymbol ABI-encodes an ERC20 symbol() call.
func PackSymbol() ([]byte, error) {
	return ERC20ABI.Pack("symbol")
}

// UnpackSymbol decodes the string result of an ERC20 symbol() call.
func UnpackSymbol(data []byte) (string, error) {
	vals, err := ERC20ABI.Unpack("symbol", data)
	if err != nil {
		return "", err
	}
	if len(vals) != 1 {
		return "", fmt.Errorf("evmnotify: unexpected symbol return")
	}
	sym, ok := vals[0].(string)
	if !ok {
		return "", fmt.Errorf("evmnotify: symbol not a string")
	}

	return sym, nil
}

// UnpackDecimals decodes the uint8 result of an ERC20 decimals call.
func UnpackDecimals(data []byte) (uint8, error) {
	vals, err := ERC20ABI.Unpack("decimals", data)
	if err != nil {
		return 0, err
	}
	if len(vals) != 1 {
		return 0, fmt.Errorf("evmnotify: unexpected decimals return")
	}
	dec, ok := vals[0].(uint8)
	if !ok {
		return 0, fmt.Errorf("evmnotify: decimals not a uint8")
	}

	return dec, nil
}

// UnpackBalanceOf decodes the uint256 result of an ERC20 balanceOf call.
func UnpackBalanceOf(data []byte) (*big.Int, error) {
	vals, err := ERC20ABI.Unpack("balanceOf", data)
	if err != nil {
		return nil, err
	}
	if len(vals) != 1 {
		return nil, fmt.Errorf("evmnotify: unexpected balanceOf return")
	}
	bal, ok := vals[0].(*big.Int)
	if !ok {
		return nil, fmt.Errorf("evmnotify: balanceOf not a uint256")
	}

	return bal, nil
}
