package evmnotify

import (
	_ "embed"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
)

// channelManagerABIJSON is the ABI of the deployed ChannelManager contract,
// generated by `forge inspect ChannelManager abi`. It is embedded so the
// adapter can pack settlement calls and parse event logs without a code-gen
// step.
//
//go:embed channelmanager_abi.json
var channelManagerABIJSON string

// ChannelManagerABI is the parsed ChannelManager ABI.
var ChannelManagerABI = mustParseABI(channelManagerABIJSON)

// erc20BalanceABI is the minimal ABI fragment needed to read an ERC20 balance.
const erc20BalanceABI = `[{"constant":true,"inputs":[{"name":"account",` +
	`"type":"address"}],"name":"balanceOf","outputs":[{"name":"",` +
	`"type":"uint256"}],"stateMutability":"view","type":"function"},` +
	`{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"",` +
	`"type":"uint8"}],"stateMutability":"view","type":"function"}]`

// ERC20ABI is the parsed minimal ERC20 ABI (balanceOf + decimals).
var ERC20ABI = mustParseABI(erc20BalanceABI)

// Event topic-0 hashes, keccak256 of the canonical event signatures. The
// adapter filters logs by these to dispatch to the right resolver.
var (
	TopicChannelOpened = crypto.Keccak256Hash([]byte(
		"ChannelOpened(bytes32,address,address,uint256,uint256)",
	))
	TopicChannelClosed = crypto.Keccak256Hash([]byte(
		"ChannelClosed(bytes32,uint256,uint256)",
	))
	TopicUnilateralCloseInitiated = crypto.Keccak256Hash([]byte(
		"UnilateralCloseInitiated(bytes32,address,uint256,uint256," +
			"uint256,uint256)",
	))
	TopicChannelPunished = crypto.Keccak256Hash([]byte(
		"ChannelPunished(bytes32,address,uint256)",
	))
	TopicHTLCClaimed = crypto.Keccak256Hash([]byte(
		"HTLCClaimed(bytes32,uint256,bytes32)",
	))
	TopicHTLCTimeout = crypto.Keccak256Hash([]byte(
		"HTLCTimeout(bytes32,uint256)",
	))
	TopicFundsDistributed = crypto.Keccak256Hash([]byte(
		"FundsDistributed(bytes32,uint256,uint256)",
	))
)

// mustParseABI parses an ABI JSON string, panicking on error (package-level
// initialisation only).
func mustParseABI(s string) abi.ABI {
	parsed, err := abi.JSON(strings.NewReader(s))
	if err != nil {
		panic("evmnotify: invalid embedded ABI: " + err.Error())
	}

	return parsed
}

// PackOpenChannel ABI-encodes an openChannel(salt, counterparty,
// localFundingAmount, remoteFundingAmount) call.
func PackOpenChannel(salt [32]byte, counterparty common.Address,
	localAmt, remoteAmt *big.Int) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"openChannel", salt, counterparty, localAmt, remoteAmt,
	)
}

// PackCloseChannel ABI-encodes a closeChannel call for a cooperative close.
func PackCloseChannel(channelID [32]byte, finalA, finalB *big.Int,
	sigA, sigB []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"closeChannel", channelID, finalA, finalB, sigA, sigB,
	)
}

// PackForceClose ABI-encodes a forceClose call.
func PackForceClose(channelID [32]byte, nonce, balA, balB *big.Int,
	htlcsHash [32]byte, sig []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"forceClose", channelID, nonce, balA, balB, htlcsHash, sig,
	)
}

// PackDistributeFunds ABI-encodes a distributeFunds call.
func PackDistributeFunds(channelID [32]byte) ([]byte, error) {
	return ChannelManagerABI.Pack("distributeFunds", channelID)
}

// PackPenalize ABI-encodes a penalize call.
func PackPenalize(channelID [32]byte, correctNonce, balA, balB *big.Int,
	htlcsHash [32]byte, correctSig []byte) ([]byte, error) {

	return ChannelManagerABI.Pack(
		"penalize", channelID, correctNonce, balA, balB, htlcsHash,
		correctSig,
	)
}

// PackBalanceOf ABI-encodes an ERC20 balanceOf(account) call.
func PackBalanceOf(account common.Address) ([]byte, error) {
	return ERC20ABI.Pack("balanceOf", account)
}

// PackDecimals ABI-encodes an ERC20 decimals() call.
func PackDecimals() ([]byte, error) {
	return ERC20ABI.Pack("decimals")
}

// UnpackDecimals decodes the uint8 result of an ERC20 decimals call.
func UnpackDecimals(data []byte) (uint8, error) {
	vals, err := ERC20ABI.Unpack("decimals", data)
	if err != nil {
		return 0, err
	}
	if len(vals) != 1 {
		return 0, fmt.Errorf("evmnotify: unexpected decimals return")
	}
	dec, ok := vals[0].(uint8)
	if !ok {
		return 0, fmt.Errorf("evmnotify: decimals not a uint8")
	}

	return dec, nil
}

// UnpackBalanceOf decodes the uint256 result of an ERC20 balanceOf call.
func UnpackBalanceOf(data []byte) (*big.Int, error) {
	vals, err := ERC20ABI.Unpack("balanceOf", data)
	if err != nil {
		return nil, err
	}
	if len(vals) != 1 {
		return nil, fmt.Errorf("evmnotify: unexpected balanceOf return")
	}
	bal, ok := vals[0].(*big.Int)
	if !ok {
		return nil, fmt.Errorf("evmnotify: balanceOf not a uint256")
	}

	return bal, nil
}
